spring.application.name=quiz_backend

# DBへの接続先
spring.datasource.url=jdbc:postgresql://localhost:5432/quiz_disney
spring.datasource.username=taku
# 先ほど psql で設定したパスワードを入力（password か postgres か確認してください）
spring.datasource.password=postgres

# 【ここを修正！】テーブルの自動生成・更新設定
# postgres ではなく update にします
spring.jpa.hibernate.ddl-auto=update

# SQLの実行ログをコンソールに出す（デバッグに便利です）
spring.jpa.show-sql=true